### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by ticky** [gmes78/libcdio-sys#1]
It looks like [there’s been an error compiling this crate’s documentation](https://docs.rs/crate/libcdio-sys/0.2.0/builds/103184), meaning that none is exposed on Crates.io, even at the URL advertised by the project’s readme: <https://docs.rs/libcdio-sys/0.2.0/libcdio_sys/>!

**Comment by MonterraByte** [comment]
The docs.rs website has an old version of libcdio installed (0.83, which is 7 years old), and to build successfully you would need to disable some bindgen options which can be enabled with later (0.90+) versions of libcdio.

The best way to get the documentation is to build it locally with `cargo doc`.

**Comment by MonterraByte** [comment]
I tried to prevent bindgen from deriving the Copy trait just for docs.rs, but it looks like the build is just completely broken for that version of libcdio (see [here](https://docs.rs/crate/libcdio-sys/0.2.2/builds/109867)).

**Comment by MonterraByte** [comment]
With the release of version 0.3.0, docs.rs now succeeds in building the documentation (although it's for an old version of libcdio).
